---
apiVersion: v1
kind: Service
metadata:
   name: jupyter-spark-svc
   namespace: default
spec:
   type: NodePort
   selector:
      app: spark
   ports:
      - port: 8888
        targetPort: 8888
        nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-spark-driver-headless
spec:
  clusterIP: None
  selector:
    app: spark