apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trino.fullname" . }}-config
data:
  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port={{ .Values.trinoPort }}
    discovery.uri=http://localhost:{{ .Values.trinoPort }}
