replicaCount: 1

image:
  repository: ghcr.io/projectnessie/nessie
  tag: "0.104.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 19120
  nodePort: 31234
  
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

versionStore:
  type: ROCKS

nodeSelector: {}
tolerations: []
affinity: {}
