{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  application.properties: |
    {{- range $key, $value := .Values.config }}
    {{ $key }} = {{ $value | quote }}
    {{- end }}
{{- end }}